### ISSUE TITLE
Error when executing the command with 'failed to find element matching selector "button[data-wikifolioid]"'

### ISSUE THREAD

**Issue by beyse** [tfabritius/wikifolio-watcher#1]
Hello good Sir!

First of all, thank you very much for sharing the code. 
I tried to run the command and it seems to work in general, however there seems to be a minor issue.
Please allow me to insert the console log, to show you what I mean. I turned on debugging in the .env file.

```
PS C:\git\wikifolio-watcher> yarn start wfobserver
yarn run v1.22.5
$ node dist/index.js wfobserver
  wikifolio-watcher:WikifolioScraper Login in to wikifolio.com (user: my-user-address@server.com)... +0ms
  wikifolio-watcher:WikifolioScraper Login successful. +9s
  wikifolio-watcher:index Processing wikifolio wfobserver +0ms
  wikifolio-watcher:WikifolioScraper Browsing: https://www.wikifolio.com/de/de/w/wfobserver +141ms
Error: Error: failed to find element matching selector "button[data-wikifolioid]"
    at ElementHandle.$eval (C:\Dev\copytrade-wikifolio\git\wikifolio-watcher\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:649:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
```

Any help on this issue is very much appreciated, Sir!
Thank you in advance and have a great day, stay healthy, Sir!

**Comment by tfabritius** [comment]
4ed7740ebbd1b0f37ac448ee18c11ad6e8480e30 should fix it.

**Comment by beyse** [comment]
Thank you Sir, this fixed the problem.
